### ISSUE TITLE
Error when running project

### ISSUE THREAD

**Issue by Tiff-C** [Tiff-C/ms3-backend-development#17]
The below errors log in the console when running the project locally. I assume this is due to the connection to the DB is not working.

```
AttributeError: 'NoneType' object has no attribute 'recipes'
127.0.0.1 - - [15/Jan/2024 17:18:10] "GET / HTTP/1.1" 500 -
127.0.0.1 - - [15/Jan/2024 17:18:10] "GET /favicon.ico HTTP/1.1" 404 -
[2024-01-15 17:18:13,148] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/ms3-backend-development/app.py", line 29, in all_recipes
    recipes = mongo.db.recipes.find()
              ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'recipes'
```

- [x] Fix db connection
- [x] Fix Server error

**Comment by Tiff-C** [comment]
Fix used this [mongoDB](https://www.mongodb.com/compatibility/setting-up-flask-with-mongodb) article. Am still not connected to the DB but am also getting the below error:

```
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in some way. To solve
this, set up an application context with app.app_context().  See the
documentation for more information.
```

This was fixed by adding `app.app_context().push()` under `app = Flask(__name__)` to give the app context.

**Comment by Tiff-C** [comment]
Fixed the app configuration using the example provided in [flask-pymongo-web-app-example](https://github.com/nyu-software-engineering/flask-pymongo-web-app-example)

The app is now trying to connect to the db but the below error is being displayed in the terminal:

```
 * MongoDB connection error: your_db_host_server_name:5000: [Errno -2] Name or service not known (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 65a7ca848d67b64a96fcf417, topology_type: Unknown, servers: [<ServerDescription ('your_db_host_server_name', 5000) server_type: Unknown, rtt: None, error=AutoReconnect('your_db_host_server_name:5000: [Errno -2] Name or service not known (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
```

Progress! 

Thanks @nyu-software-engineering

**Comment by Tiff-C** [comment]
Fixed connection error!

```
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Connected to MongoDB!
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
```

Still not reading from DB though.
